# vim  playbook1.yml
---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install httpd
    yum: name=httpd state=present
  - name: start httpd
    service: name=httpd state=started
  - name: deploy html file
    copy: src=/etc/ansible/index.html dest=/var/www/html
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted

# Execution Part:
1. syntax validator
ansible-playbook playbook1.yml --syntax-check
2. execution
ansible-playbook playbook1.yml
